---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r global_options}
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=TRUE, warning=FALSE, message=FALSE, fig.path='figure/')
```


## Loading and preprocessing the data
```{r dataPreprocess}
activityFile <- unzip("activity.zip")
activity <- read.csv(activityFile)
activityNoNA <- na.omit(activity)

```




## What is mean total number of steps taken per day?
```{r totalSteps}
library(plyr)
library(dplyr)
stepsPerDayTotal <- ddply(activityNoNA, c("date"), summarize, total = sum(steps))
summary(stepsPerDayTotal)
meanTotal <- mean(stepsPerDayTotal$total)

print(paste("mean total number of steps is ", meanTotal))
```


### Plotting the histogram ###
```{r plotHist, fig.height=5}
library(ggplot2)

g <- ggplot(stepsPerDayTotal, aes(x=total))
binsize <- 5000
theplot <- g + geom_histogram(binwidth=binsize, fill="white", color="red", origin=0)

theplot <- theplot + xlab("Total number of steps") + ggtitle("Histogram of the total number\n of steps taken each day")
theplot <- theplot + scale_y_continuous(limits=c(0, 30), breaks=seq(0,30,5))
print(theplot)

```



## What is the average daily activity pattern?
```{r dailyPattern}
by_interval <- group_by(activityNoNA, interval)
stepsPerIntervalAvg <- dplyr::summarize(by_interval, avg = mean(steps))

## find out the interval time with the maximum number of steps
intervalMax <- which(stepsPerIntervalAvg$avg == max(stepsPerIntervalAvg$avg))
intervalTime <- stepsPerIntervalAvg$interval[intervalMax]
print(paste("The interval time with the maximum number of steps is ", intervalTime))
```
### Plotting the pattern ###
```{r plotPattern}

g <- ggplot(stepsPerIntervalAvg, aes(x=interval, y=avg))
theplot <- g + geom_line(color="black") + xlab("Interval") + ylab("Average number of steps") + ggtitle("A time series plot across all days")
theplot <- theplot + annotate("rect", xmin=800, xmax=900, ymin=0, ymax=225, alpha=.1,fill="red")
theplot <- theplot + annotate("text", x=1500, y=180, label="maximum number of steps\nat the interval 835 ")
print(theplot)

```


## Imputing missing values
```{r findNA}
NAsteps <- filter(activity, is.na(steps))
print(paste("The number of records with missing values is ", nrow(NAsteps)))

## make a copy of the dataset, fill in NA steps with the mean for that 5-minute interval
activityCopy <- activity
criteria <- is.na(activityCopy$steps) & activityCopy$interval == stepsPerIntervalAvg$interval
activityCopy[criteria, c("steps")] <- stepsPerIntervalAvg$avg

stepsPerDayTotalCopy <- ddply(activityCopy, c("date"), summarize, total = sum(steps))
summary(stepsPerDayTotalCopy)
```
### Plotting the histogram ###
```{r plotHistReplaced}

g <- ggplot(stepsPerDayTotalCopy, aes(x=total))
binsize <- 5000
theplot <- g + geom_histogram(binwidth=binsize, fill="white", colour="red", origin=0)

theplot <-  theplot + xlab("Total number of steps") + ggtitle("Histogram of the total number\n of steps taken each day")
theplot <- theplot + scale_x_continuous(breaks=seq(0, 30000, 5000)) +  scale_y_continuous(limits=c(0,40), breaks=seq(0, 50, 5)) 
print(theplot)

```



## Are there differences in activity patterns between weekdays and weekends?
```{r plotPanel}
library(lubridate)
daysOfWeek <- as.factor(c("weekend", "weekday","weekday","weekday","weekday","weekday", "weekend"))
activityCopy <- mutate(activityCopy, daytype = daysOfWeek[wday(date)])

stepsBydaytype <- ddply(activityCopy, c("daytype","interval"), summarize, avg = mean(steps))

### Display the panel plot ###

g <- ggplot(stepsBydaytype, aes(x=interval, y=avg))
theplot <- g + geom_line(color="red") + labs(x="Interval", y="Average number of steps") + facet_wrap(~daytype, nrow=2)

theplot <- theplot + scale_x_continuous(limits=c(0,2355), breaks=seq(0, 2355, 250))

print(theplot)

```

